# Generated by Django 2.2.23 on 2021-05-20 16:18

from django.db import migrations, models
import multisite.models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='is_canonical',
            field=models.BooleanField(default=None, editable=False, help_text='Does this domain name match the one in site?', null=True, validators=[multisite.models.validate_true_or_none], verbose_name='is canonical?'),
        ),
    ]
